import React from 'react'
import type { PatientDetail } from '../lib/api'
import type { RxDraft } from './PrescriptionBuilder'

const PrintSheet: React.FC<{ patient: PatientDetail; draft: RxDraft }> = ({ patient, draft }) => (
  <div id="print-area" className="hidden print:block bg-white text-slate-900" style={{ padding: '28px 34px' }}>
    {/* letterhead */}
    <div className="flex items-center justify-between border-b-2 border-teal-700 pb-3">
      <div className="flex items-center gap-3">
        <div className="w-11 h-11 rounded-lg bg-teal-700 text-white font-extrabold flex items-center justify-center text-xl">S</div>
        <div>
          <div className="text-xl font-extrabold text-teal-800">SwasthAI Hospital</div>
          <div className="text-[11px] text-slate-500">ABDM-linked · Voice-first AI Case-Taking Kiosk</div>
        </div>
      </div>
      <div className="text-right text-[11px] text-slate-500">
        <div className="font-bold text-slate-700 text-sm">Dr. A. Verma</div>
        <div>MBBS, MD · General Medicine</div>
        <div>Reg. No. 12345</div>
      </div>
    </div>

    {/* patient row */}
    <div className="grid grid-cols-3 gap-3 text-[12px] mt-3 pb-3 border-b border-slate-200">
      <div><span className="text-slate-400">Patient:</span> <b>{patient.name}</b></div>
      <div><span className="text-slate-400">Age / Sex:</span> <b>{patient.age ?? '—'} / {patient.gender}</b></div>
      <div><span className="text-slate-400">Date:</span> <b>{new Date().toLocaleDateString()}</b></div>
      <div className="col-span-2"><span className="text-slate-400">ABHA:</span> <b>{patient.abhaId}</b></div>
      {patient.allergies.length > 0 && <div className="text-red-600"><b>Allergies:</b> {patient.allergies.join(', ')}</div>}
    </div>

    {draft.diagnosis && <div className="text-[12px] mt-3"><span className="text-slate-400">Diagnosis:</span> <b>{draft.diagnosis}</b></div>}

    {/* Rx */}
    <div className="mt-2">
      <div className="text-3xl font-serif text-teal-800" style={{ fontFamily: 'Georgia, serif' }}>℞</div>
      <table className="w-full text-[12.5px] mt-1">
        <thead>
          <tr className="text-left text-slate-400 border-b border-slate-200">
            <th className="py-1 w-6">#</th><th className="py-1">Medicine</th><th className="py-1">Dose</th>
            <th className="py-1">Frequency</th><th className="py-1">When</th><th className="py-1">Duration</th>
          </tr>
        </thead>
        <tbody>
          {draft.meds.map((m, i) => (
            <tr key={i} className="border-b border-slate-100">
              <td className="py-1.5">{i + 1}</td>
              <td className="py-1.5 font-semibold">{m.name}</td>
              <td className="py-1.5">{m.dosage}</td>
              <td className="py-1.5">{m.frequency}</td>
              <td className="py-1.5">{m.timing}</td>
              <td className="py-1.5">{m.duration}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>

    {draft.advice && (
      <div className="text-[12px] mt-4"><span className="text-slate-400 font-semibold">Advice:</span> {draft.advice}</div>
    )}

    <div className="flex justify-end mt-14">
      <div className="text-center">
        <div className="border-t border-slate-400 w-48 pt-1 text-[11px] text-slate-500">Doctor's signature</div>
      </div>
    </div>
    <div className="text-center text-[10px] text-slate-400 mt-6 border-t border-slate-200 pt-2">
      Generated by SwasthAI · This prescription is saved to the patient's ABHA health record.
    </div>
  </div>
)

export default PrintSheet
